### ISSUE TITLE
Missing "./lib/types" specifier in "vue-sonner" package with Nuxt 3.8.0

### ISSUE THREAD

**Issue by xxxxxaaaaaaaannnn** [wobsoriano/vuetify-sonner#11]
Since I upgraded to Nuxt 3.8.0, it's not working anymore

`[plugin:vite:import-analysis] Missing "./lib/types" specifier in "vue-sonner" package

/Users/x/VisualStudioProjects/app_vue/components/notifications/VSonner.vue

    at e (file:///Users/x/VisualStudioProjects/app_vue/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:21445:25)
    at n (file:///Users/x/VisualStudioProjects/app_vue/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:21445:627)
    at o (file:///Users/x/VisualStudioProjects/app_vue/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:21445:1297)
    at resolveExportsOrImports (file:///Users/x/VisualStudioProjects/app_vue/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28746:20)
    at resolveDeepImport (file:///Users/x/VisualStudioProjects/app_vue/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28765:31)
    at tryNodeResolve (file:///Users/x/VisualStudioProjects/app_vue/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28453:20)
    at Context.resolveId (file:///Users/x/VisualStudioProjects/app_vue/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28212:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.resolveId (file:///Users/x/VisualStudioProjects/app_vue/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44276:32)
    at async TransformContext.resolve (file:///Users/x/VisualStudioProjects/app_vue/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:43992:23`

**Comment by xxxxxaaaaaaaannnn** [comment]
Nevermind, I poorly implemented Position
